version: '3.1'
services:
  db:
    image: postgres:16-alpine
    container_name: habit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=habit-db
      - POSTGRES_USER=constantin
      - POSTGRES_PASSWORD=password
